# Generated by Django 3.2.5 on 2021-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_userfollowings_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowings',
            name='value',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Unfollow', 'Unfollow')], default='Follow', max_length=10),
        ),
    ]
