# Generated by Django 3.2.5 on 2021-07-27 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_userfollowings_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(related_name='_User_profile_follow_+', to=settings.AUTH_USER_MODEL, verbose_name='follow'),
        ),
    ]
